/**
 * Mermaid Sanitizer & Auto-Repair Utility
 * Fixes common syntax mistakes generated by LLMs such as:
 * - Unquoted node labels containing special characters (/, :, ;, &, (, ), etc.)
 * - Invalid arrow notations in flowcharts (e.g., -->>, <<--, ==>>)
 * - Semicolons joining multiple statements on a single line
 * - Missing diagram headers (defaults to flowchart TD)
 * - Raw markdown code blocks / fences accidentally left in
 */

export function sanitizeMermaidCode(raw: string): string {
  if (!raw || typeof raw !== 'string') return '';

  // 1. Strip markdown fences and whitespace
  let clean = raw.trim();
  clean = clean.replace(/^```(?:mermaid)?\s*\n?/i, '').replace(/\n?```\s*$/i, '').trim();

  // 2. Strip HTML comments
  clean = clean.replace(/<!--[\s\S]*?-->/g, '');

  if (!clean) return '';

  // 3. Ensure valid diagram header
  const diagramKeywords = [
    'flowchart', 'graph', 'sequencediagram', 'classdiagram',
    'statediagram', 'statediagram-v2', 'erdiagram', 'gantt',
    'pie', 'gitgraph', 'journey', 'mindmap', 'quadrantchart',
    'architecture', 'c4context', 'c4container', 'c4component',
    'c4dynamic', 'c4deployment', 'block', 'block-beta', 'xychart-beta', 'kanban', 'sankey-beta'
  ];

  const lines = clean.split('\n');
  const firstNonEmpty = lines.find(l => l.trim().length > 0) || '';
  const firstWord = firstNonEmpty.trim().toLowerCase().split(/[\s(;:]+/)[0];
  const hasDiagramHeader = diagramKeywords.some(kw => firstWord.startsWith(kw));

  if (!hasDiagramHeader) {
    clean = 'flowchart TD\n' + clean;
  }

  const isFlowOrGraph = /^\s*(flowchart|graph)\b/i.test(clean);

  if (isFlowOrGraph) {
    const rawLines = clean.split('\n');
    const processedLines: string[] = [];

    rawLines.forEach((line, idx) => {
      // Preserve first header line (e.g. "flowchart TD" or "graph LR")
      if (idx === 0 && /^\s*(flowchart|graph)\b/i.test(line)) {
        processedLines.push(line.trim());
        return;
      }

      if (!line.trim()) {
        processedLines.push('');
        return;
      }

      let l = line;

      // 1. Fix common invalid arrow permutations in flowcharts
      l = l.replace(/-->>/g, '-->');
      l = l.replace(/<<--/g, '<--');
      l = l.replace(/==>>/g, '==>');
      l = l.replace(/<<==/g, '<==');

      // 2. Split statements joined by semicolons outside quotes
      let inQuotes = false;
      let splitResult = '';
      for (let i = 0; i < l.length; i++) {
        const char = l[i];
        if (char === '"' && (i === 0 || l[i - 1] !== '\\')) {
          inQuotes = !inQuotes;
          splitResult += char;
        } else if (char === ';' && !inQuotes) {
          splitResult += '\n';
        } else {
          splitResult += char;
        }
      }

      const subLines = splitResult.split('\n');
      for (let sub of subLines) {
        let subLine = sub.trim();
        if (!subLine) continue;

        // 3. Fix unquoted square brackets: NodeID[Some / Text] -> NodeID["Some / Text"]
        subLine = subLine.replace(/\b([A-Za-z0-9_$-]+)\s*\[\s*([^"\]\n]+?)\s*\]/g, (match, id, text) => {
          const trimmed = text.trim();
          if (trimmed.startsWith('"') && trimmed.endsWith('"')) return match;
          const safe = trimmed.replace(/"/g, '\\"');
          return `${id}["${safe}"]`;
        });

        // 4. Fix unquoted round brackets: NodeID(Some / Text) -> NodeID("Some / Text")
        subLine = subLine.replace(/\b([A-Za-z0-9_$-]+)\s*\(\s*([^"\)\n]+?)\s*\)/g, (match, id, text) => {
          const trimmed = text.trim();
          if (['td', 'lr', 'rl', 'bt', 'tb', 'subgraph'].includes(id.toLowerCase())) return match;
          if (trimmed.startsWith('"') && trimmed.endsWith('"')) return match;
          const safe = trimmed.replace(/"/g, '\\"');
          return `${id}("${safe}")`;
        });

        // 5. Fix unquoted curly braces: NodeID{Some / Text} -> NodeID{"Some / Text"}
        subLine = subLine.replace(/\b([A-Za-z0-9_$-]+)\s*\{\s*([^"\}\n]+?)\s*\}/g, (match, id, text) => {
          const trimmed = text.trim();
          if (trimmed.startsWith('"') && trimmed.endsWith('"')) return match;
          const safe = trimmed.replace(/"/g, '\\"');
          return `${id}{"${safe}"}`;
        });

        processedLines.push('  ' + subLine);
      }
    });

    clean = processedLines.join('\n');
  }

  return clean;
}
