import type { LensState, LensPreset } from './types';

export function getInitialLensState(preset: LensPreset = 'adr'): LensState {
  return {
    id: `lens-${Date.now()}`,
    title: preset === 'threat_model'
      ? 'Security & Threat Model'
      : preset === 'research'
      ? 'System Research & Architecture'
      : 'Architecture Decision (ADR)',
    preset,
    activeView: 'architecture',
    selectedComponentId: undefined,
    theme: 'dark',
    updatedAt: new Date().toISOString(),

    // 17 Nodes matching Screenshot 1 & 3
    components: [
      {
        id: 'admin_user',
        name: 'Admin User',
        subtitle: 'Arbitrary claim injection / DDoS',
        type: 'actor',
        category: 'external_network',
        x: 60,
        y: 160,
        width: 170,
        height: 80,
      },
      {
        id: 'rogue_user',
        name: 'Rogue User',
        subtitle: 'Arbitrary claim injection / DDoS',
        type: 'actor',
        category: 'external_network',
        x: 60,
        y: 280,
        width: 170,
        height: 80,
      },
      {
        id: 'client',
        name: 'Client',
        subtitle: 'Client application runtime',
        type: 'client',
        category: 'service_process',
        boundaryId: 'public_dmz',
        x: 520,
        y: 140,
        width: 220,
        height: 90,
        threatCount: 4,
      },
      {
        id: 'api_gateway',
        name: 'API Gateway',
        subtitle: 'API Gateway',
        type: 'gateway',
        category: 'service_process',
        x: 520,
        y: 300,
        width: 220,
        height: 90,
        threatCount: 1,
      },
      {
        id: 'istio_gateway',
        name: 'istio gateway',
        subtitle: 'mTLS termination',
        type: 'gateway',
        category: 'service_process',
        boundaryId: 'internal_mesh',
        x: 500,
        y: 450,
        width: 200,
        height: 85,
      },
      {
        id: 'policy_store',
        name: 'Policy Store',
        subtitle: 'Persistence',
        type: 'datastore',
        category: 'database_store',
        boundaryId: 'internal_mesh',
        x: 230,
        y: 630,
        width: 180,
        height: 85,
        threatCount: 1,
      },
      {
        id: 'web_server',
        name: 'Web Server',
        subtitle: 'Request Validation and Processing',
        type: 'service',
        category: 'service_process',
        boundaryId: 'internal_mesh',
        x: 500,
        y: 630,
        width: 210,
        height: 85,
        threatCount: 1,
      },
      {
        id: 'secure_key_mgmt',
        name: 'Secure Key Management',
        subtitle: 'Provisioning, patching, maintenance',
        type: 'security',
        category: 'service_process',
        boundaryId: 'internal_mesh',
        x: 740,
        y: 560,
        width: 200,
        height: 90,
      },
      {
        id: 'in_memory_cache',
        name: 'In Memory Key Storage',
        subtitle: 'In-Memory Cache',
        type: 'datastore',
        category: 'database_store',
        boundaryId: 'internal_mesh',
        x: 740,
        y: 680,
        width: 190,
        height: 85,
        threatCount: 3,
      },
      {
        id: 'kms',
        name: 'KMS',
        subtitle: 'Key Management',
        type: 'security',
        category: 'service_process',
        boundaryId: 'internal_mesh',
        x: 500,
        y: 770,
        width: 190,
        height: 85,
        threatCount: 2,
      },
      {
        id: 'web_cosmos_db',
        name: 'Web Cosmos DB',
        subtitle: 'Store encrypted Google TINK Keyset KEKs',
        type: 'datastore',
        category: 'database_store',
        boundaryId: 'public_dmz_db',
        x: 290,
        y: 890,
        width: 190,
        height: 85,
      },
      {
        id: 'database',
        name: 'Database',
        subtitle: 'Persistence',
        type: 'datastore',
        category: 'database_store',
        boundaryId: 'public_dmz_db',
        x: 540,
        y: 890,
        width: 170,
        height: 85,
      },
      {
        id: 'managed_hsm',
        name: 'Managed HSM',
        subtitle: 'Hardware Security Module',
        type: 'security',
        category: 'service_process',
        x: 490,
        y: 1020,
        width: 190,
        height: 80,
      },
      {
        id: 'logging_monitoring',
        name: 'Logging and Monitoring',
        subtitle: 'Service Component',
        type: 'service',
        category: 'service_process',
        boundaryId: 'trust_boundary',
        x: 770,
        y: 890,
        width: 180,
        height: 85,
      },
      {
        id: 'alerts',
        name: 'Alerts',
        subtitle: 'Alerting dispatch',
        type: 'service',
        category: 'service_process',
        boundaryId: 'trust_boundary',
        x: 770,
        y: 1010,
        width: 180,
        height: 80,
      },
      {
        id: 'asset',
        name: 'Asset',
        subtitle: 'Protected',
        type: 'asset',
        category: 'service_process',
        x: 780,
        y: 140,
        width: 170,
        height: 85,
      },
      {
        id: 'end_user_devices',
        name: 'End user devices',
        subtitle: 'Protected',
        type: 'asset',
        category: 'service_process',
        x: 780,
        y: 260,
        width: 170,
        height: 85,
      },
    ],

    // 4 Boundaries matching Screenshot 1
    boundaries: [
      {
        id: 'public_dmz',
        title: 'PUBLIC DMZ INGRESS BOUNDARY',
        subtitle: '• Network Perimeter',
        color: 'orange',
        x: 480,
        y: 100,
        width: 300,
        height: 160,
        componentIds: ['client'],
      },
      {
        id: 'internal_mesh',
        title: 'DATA PERSISTENCE & SECRETS',
        subtitle: '• Storage Enclave',
        color: 'blue',
        x: 180,
        y: 400,
        width: 790,
        height: 480,
        componentIds: ['istio_gateway', 'policy_store', 'web_server', 'secure_key_mgmt', 'in_memory_cache', 'kms'],
      },
      {
        id: 'public_dmz_db',
        title: 'PUBLIC DMZ INGRESS BOUNDARY',
        subtitle: '• Network Perimeter',
        color: 'orange',
        x: 250,
        y: 850,
        width: 480,
        height: 160,
        componentIds: ['web_cosmos_db', 'database'],
      },
      {
        id: 'trust_boundary',
        title: 'TRUST BOUNDARY',
        subtitle: '• Network Perimeter',
        color: 'orange',
        x: 745,
        y: 850,
        width: 230,
        height: 260,
        componentIds: ['logging_monitoring', 'alerts'],
      },
    ],

    // Wires / Connections matching Screenshot 1
    connections: [
      { id: 'w1', from: 'admin_user', to: 'client', label: 'Privileged escalation of perm', style: 'dashed', color: '#ef4444' },
      { id: 'w2', from: 'rogue_user', to: 'client', label: 'exploits', style: 'dashed', color: '#ef4444' },
      { id: 'w3', from: 'client', to: 'api_gateway', label: 'calls', color: '#3b82f6' },
      { id: 'w4', from: 'api_gateway', to: 'istio_gateway', label: 'calls', color: '#6b7280' },
      { id: 'w5', from: 'istio_gateway', to: 'web_server', label: 'encrypt call', color: '#6b7280' },
      { id: 'w6', from: 'web_server', to: 'policy_store', label: 'authorize', color: '#6b7280' },
      { id: 'w7', from: 'web_server', to: 'kms', label: 'calls', color: '#6b7280' },
      { id: 'w8', from: 'kms', to: 'web_server', label: 'Decrypt KEK', color: '#6b7280' },
      { id: 'w9', from: 'kms', to: 'in_memory_cache', label: 'stores', color: '#6b7280' },
      { id: 'w10', from: 'kms', to: 'managed_hsm', label: 'Decrypt KEK', color: '#6b7280' },
      { id: 'w11', from: 'kms', to: 'web_cosmos_db', label: 'Get Encrypted KEK', color: '#6b7280' },
      { id: 'w12', from: 'web_server', to: 'database', label: 'persistence', color: '#6b7280' },
      { id: 'w13', from: 'logging_monitoring', to: 'alerts', label: 'triggers', color: '#6b7280' },
      { id: 'w14', from: 'in_memory_cache', to: 'secure_key_mgmt', label: 'exploits', style: 'dashed', color: '#ef4444' },
    ],

    // Notes on canvas
    notes: [
      {
        id: 'n1',
        text: 'mTLS is enabled across the architecture',
        x: 740,
        y: 420,
        width: 170,
        height: 70,
      },
      {
        id: 'n2',
        text: 'Ensuring customer-managed keys are implemented using FIPS 140-3 validated hardware offers strong cryptographic isolation within each tenant\'s environment.',
        x: 180,
        y: 860,
        width: 180,
        height: 140,
      },
    ],

    // 8 Threats matching Screenshot 2
    threats: [
      {
        id: 'THB-01',
        title: '[Policy Store] Trust Boundary Analysis',
        componentId: 'policy_store',
        componentName: 'Policy Store',
        category: 'Elevation of Privilege',
        threatActor: 'Compromised Service / Rogue Process',
        attackVector: 'Cross-boundary tampering and unauthorized privilege escalation',
        targetedAsset: 'Policy Definitions & Access Rule Repository',
        description: 'Unauthorized cross-boundary calls attempt to alter access rules or bypass security checks.',
        mitigation: 'Strict mTLS policy validation, hardware cryptographic attestation, and continuous invariant verification.',
        linkedAdrId: 'ADR-01',
        enforcingInvariantId: 'INV-01',
        severity: 'High',
        likelihood: 'Medium',
        risk: 'High',
        status: 'Open',
        isPinned: true,
        url: 'https://cwe.mitre.org/data/definitions/250.html',
      },
      {
        id: 'THR-10',
        title: 'Cryptographic Exhaustion / KEK Compromise',
        componentId: 'kms',
        componentName: 'KMS',
        category: 'Info Disclosure',
        threatActor: 'Advanced Persistent Threat (APT)',
        attackVector: 'Side-channel or memory extraction of ephemeral key material',
        targetedAsset: 'Key Encryption Key (KEK) & DEKs',
        description: 'Long-lived key usage could enable ciphertext exhaustion or memory analysis during decrypt operations.',
        mitigation: 'Automated 90-day KEK rotation, ephemeral session DEKs, and FIPS 140-3 HSM master keys.',
        linkedAdrId: 'ADR-07',
        enforcingInvariantId: 'INV-07',
        severity: 'High',
        likelihood: 'Low',
        risk: 'Medium',
        status: 'Open',
        isPinned: false,
        url: 'https://csrc.nist.gov/publications/detail/fips/140/3/final',
      },
      {
        id: 'THR-09',
        title: 'Unauthorized Key Decryption Request',
        componentId: 'kms',
        componentName: 'KMS',
        category: 'Elevation of Privilege',
        threatActor: 'Compromised Service / Rogue Process',
        attackVector: 'Direct RPC replay to KMS decrypt API',
        targetedAsset: 'Master Key Encryption Key (KEK)',
        description: 'An attacker compromising internal mesh tokens could replay decryption requests to decrypt sensitive tenant secrets without authorization.',
        mitigation: 'Hardware-backed envelope decryption with strict caller identity binding, attested tokens, and HSM verification.',
        linkedAdrId: 'ADR-07',
        enforcingInvariantId: 'INV-07',
        severity: 'Critical',
        likelihood: 'Medium',
        risk: 'High',
        status: 'Open',
        isPinned: true,
        url: 'https://docs.aws.amazon.com/kms/latest/developerguide/',
      },
      {
        id: 'THR-08',
        title: 'Privileged access',
        componentId: 'client',
        componentName: 'Client',
        category: 'Elevation of Privilege',
        threatActor: 'External Network',
        attackVector: 'Privileged escalation of permissions',
        targetedAsset: 'Client Credentials and Session Tokens',
        description: 'EXTERNAL NETWORK: Privileged escalation of permissions targeting client.',
        mitigation: 'Periodic PUM and user access review',
        severity: 'High',
        likelihood: 'High',
        risk: 'High',
        status: 'Open',
        isPinned: true,
        url: 'https://cwe.mitre.org/data/definitions/250.html',
      },
      {
        id: 'THR-07',
        title: 'Unauthorized System Access',
        componentId: 'client',
        componentName: 'Client',
        category: 'Spoofing',
        threatActor: 'External Network',
        attackVector: 'exploits targeting client',
        targetedAsset: 'Transaction data in PostgreSQL',
        description: 'EXTERNAL NETWORK: exploits targeting client.',
        mitigation: 'Strict identity validation and device attestation.',
        severity: 'High',
        likelihood: 'High',
        risk: 'High',
        status: 'Open',
        isPinned: true,
        url: 'https://cwe.mitre.org/data/definitions/287.html',
      },
      {
        id: 'THR-06',
        title: 'Unauthorized System Access',
        componentId: 'note_aa594b',
        componentName: 'Note (Client)',
        category: 'Spoofing',
        threatActor: 'External Network',
        attackVector: 'exploits targeting note_22594b',
        description: 'EXTERNAL NETWORK: exploits targeting note_22594b.',
        mitigation: 'Validate note boundaries and integrity check.',
        severity: 'High',
        likelihood: 'High',
        risk: 'High',
        status: 'Open',
        isPinned: true,
      },
      {
        id: 'THR-05',
        title: 'Attacker with infrastructure access able to do memory dump and get the raw keys',
        componentId: 'in_memory_cache',
        componentName: 'In Memory Key Storage',
        category: 'Info Disclosure',
        threatActor: 'Hypothetical Threat Actor',
        attackVector: 'Attacker with infrastructure access able to do memory dump and get the raw keys',
        description: 'An attacker able to target In Memory Key Storage via Attacker with infrastructure access able to do memory dump and get the raw keys could bypass existing perimeter controls, leading to unauthorized state alteration or data exposure.',
        mitigation: 'Implement strict validation controls, cryptographic isolation, and audit telemetry for In Memory Key Storage.',
        linkedAdrId: 'ADR-06',
        severity: 'High',
        likelihood: 'Medium',
        risk: 'Medium',
        status: 'Open',
        isPinned: false,
      },
      {
        id: 'THR-04',
        title: 'API Key Impersonation & Spoofing on API Gateway',
        componentId: 'api_gateway',
        componentName: 'API Gateway',
        category: 'Spoofing',
        threatActor: 'Hypothetical Threat Actor',
        attackVector: 'API Key Impersonation & Spoofing',
        description: 'An attacker able to target API Gateway via API Key Impersonation & Spoofing could bypass existing perimeter controls, leading to unauthorized state alteration or data exposure.',
        mitigation: 'Implement strict validation controls, cryptographic isolation, and audit telemetry for API Gateway.',
        severity: 'High',
        likelihood: 'Medium',
        risk: 'Medium',
        status: 'Open',
        isPinned: false,
      },
      {
        id: 'THR-03',
        title: 'Broken Object-Level Authorization (BOLA) & Scope Escalation',
        componentId: 'web_server',
        componentName: 'Web Server',
        category: 'Elevation of Privilege',
        threatActor: 'Authenticated Tenant / Rogue User',
        attackVector: 'Direct object reference parameter manipulation',
        description: 'An attacker possessing valid low-privilege credentials could manipulate record identifiers when calling Web Server, accessing tenant resources outside their authorized scope.',
        mitigation: 'Validate tenant isolation and fine-grained ABAC permissions on every handler before executing business logic.',
        linkedAdrId: 'ADR-05',
        severity: 'Critical',
        likelihood: 'High',
        risk: 'Critical',
        status: 'Open',
        isPinned: false,
      },
      {
        id: 'THR-02',
        title: 'Session Hijacking & Cross-Site Scripting (XSS)',
        componentId: 'client',
        componentName: 'Client',
        category: 'Spoofing',
        threatActor: 'Web Attacker / Malicious Script',
        attackVector: 'Reflected / Stored script injection in UI context',
        description: 'An attacker able to inject malicious script payloads into Client could capture active session tokens and impersonate legitimate operators.',
        mitigation: 'Store tokens in HTTP-only Secure SameSite cookies, implement strict Content Security Policy (CSP), and enforce context escaping.',
        severity: 'High',
        likelihood: 'Medium',
        risk: 'Medium',
        status: 'Open',
        isPinned: false,
      },
      {
        id: 'THR-01',
        title: 'SQL Injection Attack',
        componentId: 'client',
        componentName: 'Client',
        category: 'Tampering',
        threatActor: 'Untrusted Attacker',
        attackVector: 'sql injection',
        description: 'An attacker able to exploit sql injection against Client could bypass security boundaries, leading to unauthorized state mutation or data exposure.',
        mitigation: 'Implement strict input validation, parameterized queries, and boundary isolation.',
        severity: 'High',
        likelihood: 'Medium',
        risk: 'Medium',
        status: 'Open',
        isPinned: false,
      },
    ],

    // Decisions / ADRs matching Screenshot 2
    decisions: [
      {
        id: 'ADR-01',
        title: 'Mitigation for Policy Store Trust Boundary Analysis',
        componentId: 'policy_store',
        componentName: 'Policy Store',
        approach: 'Approach: Enforce envelope encryption with hardware cryptographic verification and automated audit replication for all policy rules.',
        rationale: 'Guarantees policy immutability and prevents cross-boundary authorization bypass.',
        alternatives: 'Direct in-memory cache without replication, optimistic concurrency validation.',
        status: 'Approved',
        isPinned: true,
        url: 'https://cloud.google.com/kms/docs/envelope-encryption',
      },
      {
        id: 'ADR-07',
        title: 'Envelope Encryption with Split-Key Architecture',
        componentId: 'kms',
        componentName: 'KMS',
        approach: 'Approach: Implement envelope encryption using master KEK in HSM and ephemeral DEKs for Web Server sessions.',
        rationale: 'Eliminates plaintext key exposure over transport and minimizes KMS decrypt request latency.',
        alternatives: 'Direct database-level column encryption with shared static keys.',
        status: 'Approved',
        isPinned: true,
        url: 'https://cloud.google.com/kms/docs/envelope-encryption',
      },
      {
        id: 'ADR-06',
        title: 'Cache Defence to mitigate THR-05',
        componentId: 'in_memory_cache',
        componentName: 'In Memory Key Storage',
        approach: 'Approach: Implementing a secure in-memory key storage solution.',
        rationale: 'To prevent unauthorized access to sensitive keys stored in memory during runtime, we need a robust approach that ensures strong encryption.',
        alternatives: 'Alternatives: No action, Use less secure in-memory storage',
        status: 'Proposed',
        isPinned: true,
      },
      {
        id: 'ADR-05',
        title: 'Decision for Mitigating THR-03',
        componentId: 'web_server',
        componentName: 'Web Server',
        approach: 'Approach: Implement Role-Based Access Control (RBAC)',
        rationale: 'Role-Based Access Control ensures that users can only access data and perform actions they are explicitly granted permission to do.',
        alternatives: 'Alternatives: None',
        status: 'Proposed',
        isPinned: false,
      },
      {
        id: 'ADR-04',
        title: 'Key Rotation Strategy for Managed HSM',
        componentId: 'managed_hsm',
        componentName: 'Managed HSM',
        approach: 'Approach: Engineered Architectural Approach for Key Rotation',
        rationale: 'Addresses architectural trade-offs while fulfilling system reliability and operational requirements.',
        alternatives: 'Alternatives: Alternative Implementation A, Alternative Implementation B',
        status: 'Approved',
        isPinned: false,
      },
      {
        id: 'ADR-03',
        title: 'Identity & Authentication Architecture for istio gateway',
        componentId: 'istio_gateway',
        componentName: 'istio gateway',
        approach: 'Approach: Zero-Trust mTLS with Asymmetric RS256 JWT Identity Tokens',
        rationale: 'Decentralizes token cryptographic verification to edge and service boundaries without bottlenecking an auth server.',
        alternatives: 'Alternatives: Opaque Session Cookies, Shared API Key Bearer Tokens, Basic Auth',
        status: 'Approved',
        isPinned: false,
      },
      {
        id: 'ADR-02',
        title: 'Circuit Breaker Pattern Strategy for Client',
        componentId: 'client',
        componentName: 'Client',
        approach: 'Approach: Engineered Architectural Approach for Circuit Breaker Pattern',
        rationale: 'Addresses architectural trade-offs while fulfilling system reliability and operational requirements.',
        alternatives: 'Alternatives: Alternative Implementation A, Alternative Implementation B',
        status: 'Approved',
        isPinned: true,
      },
      {
        id: 'ADR-08',
        title: 'Grpc Vs Rest Communication Strategy for Client',
        componentId: 'client',
        componentName: 'Client',
        approach: 'Approach: Engineered Architectural Approach for gRPC vs REST Communication',
        rationale: 'Addresses architectural trade-offs while fulfilling system reliability and operational requirements.',
        alternatives: 'Alternatives: Alternative Implementation A, Alternative Implementation B',
        status: 'Approved',
        isPinned: true,
        url: 'https://grpc.io/docs/guides/',
      },
    ],

    // Invariants matching Screenshot 2
    invariants: [
      {
        id: 'INV-02',
        title: 'Data Consistency',
        componentId: 'policy_store',
        componentName: 'Policy Store',
        statement: 'Policy Store persistence guarantees strong transactional consistency across all replicated storage volumes with zero drift.',
        category: 'Automated Policy / Runtime Verification',
        enforcementMechanism: 'Raft consensus transactional replication with atomic fsync commits',
        status: 'Enforced',
        isPinned: true,
        url: 'https://raft.github.io/',
      },
      {
        id: 'INV-01',
        title: '[Policy Store] Data Integrity Invariant',
        componentId: 'policy_store',
        componentName: 'Policy Store',
        statement: 'Every policy alteration must be verified against cryptographic hash trees prior to storage state commitment.',
        category: 'Synchronous fsync commit semantics on the primary datastore',
        enforcementMechanism: 'Cryptographic Merkle tree verification & signed payload validation',
        status: 'Enforced',
        isPinned: true,
        url: 'https://www.postgresql.org/docs/current/wal-intro.html',
      },
      {
        id: 'INV-07',
        title: 'Root Key Non-Exportability Guarantee',
        componentId: 'kms',
        componentName: 'KMS',
        statement: 'Key Encryption Keys (KEK) can never leave the secure hardware cryptographic boundary in unencrypted form under any circumstances.',
        category: 'Hardware Security Module Isolation',
        enforcementMechanism: 'Hardware boundary isolation & non-exportable flag enforcement',
        status: 'Enforced',
        isPinned: true,
        url: 'https://csrc.nist.gov/',
      },
      {
        id: 'INV-06',
        title: 'Cache Eviction Policies Misconfiguration',
        componentId: 'in_memory_cache',
        componentName: 'In Memory Key Storage',
        statement: 'Cache Eviction Policies Misconfiguration: Incorrect configuration of eviction strategies like LRU (Least Recently Used) could result in evicting frequently accessed items from memory, causing performance degradation.',
        category: 'Cache Eviction Policies Misconfiguration',
        enforcementMechanism: 'Cache Eviction Policies Misconfiguration',
        status: 'Enforced',
        isPinned: true,
        url: 'https://redis.io/docs/reference/eviction/',
      },
      {
        id: 'INV-05',
        title: 'Invariant for Managed HSM',
        componentId: 'managed_hsm',
        componentName: 'Managed HSM',
        statement: 'Hardware cryptographic boundaries must enforce physical tamper detection and zeroization of master root keys.',
        category: 'Automated Policy / Runtime Verification',
        enforcementMechanism: 'FIPS 140-3 Hardware Boundary Isolation',
        status: 'Enforced',
        isPinned: false,
        url: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program',
      },
      {
        id: 'INV-04',
        title: 'Zero Key Loss on Hardware failure',
        componentId: 'managed_hsm',
        componentName: 'Managed HSM',
        statement: 'Hardware failure leading to loss of data if not properly handled in the HSM architecture. Each partition must be regularly checked for health status and failover mechanisms must execute with zero data loss.',
        category: 'Automated Policy / Runtime Verification',
        enforcementMechanism: 'Partition health heartbeat & synchronous cluster replication',
        status: 'Enforced',
        isPinned: true,
        url: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program',
      },
      {
        id: 'INV-03',
        title: 'Ensuring customer-managed keys are implemented',
        componentId: 'managed_hsm',
        componentName: 'Managed HSM',
        statement: 'Ensuring customer-managed keys are implemented using FIPS 140-3 validated hardware offers strong cryptographic isolation within each tenant\'s environment, highlighting key risks related to permanent loss if control over components changes hands.',
        category: 'Automated Policy / Runtime Verification',
        enforcementMechanism: 'Per-tenant partition isolation & HSM cryptographic verification',
        status: 'Enforced',
        isPinned: false,
        url: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program',
      },
      {
        id: 'INV-09',
        title: 'Key Sovereignty',
        componentId: 'managed_hsm',
        componentName: 'Managed HSM',
        statement: 'Customer-managed keys are implemented using FIPS 140-3 validated hardware which offers strong cryptographic isolation for each customer\'s key material within the service.',
        category: 'Automated Policy / Runtime Verification',
        enforcementMechanism: 'Tenant-isolated hardware keyspace attestation',
        status: 'Enforced',
        isPinned: false,
        url: 'https://csrc.nist.gov/projects/cryptographic-module-validation-program',
      },
      {
        id: 'INV-08',
        title: 'State Durability & Write-Ahead Log Integrity',
        componentId: 'database',
        componentName: 'Database',
        statement: 'Every mutating operation on Database must be synchronously committed to the WAL before an acknowledgment is returned to the client.',
        category: 'Synchronous fsync commit semantics on the primary datastore',
        enforcementMechanism: 'PostgreSQL WAL fsync synchronous commit guarantees',
        status: 'Enforced',
        isPinned: false,
        url: 'https://www.postgresql.org/docs/current/wal-intro.html',
      },
    ],

    findings: [],

    documentMarkdown: `# Architecture Decision Record (ADR)
## System Overview & Boundary Design

### 1. Executive Scope
This document captures the architectural decisions, trust boundaries, threat models, and operational invariants for the distributed service mesh.

### 2. Network Topology & Perimeters
- **Public DMZ Ingress Boundary**: Isolates public ingress traffic via Client and API Gateway.
- **Internal Service Mesh Boundary**: Enforces mutual TLS (mTLS) zero-trust communication across Web Server, KMS, In-Memory Storage, and Policy Store.
- **Trust Boundary**: Isolates audit logging and alert dispatching mechanisms.

### 3. Key Decisions
- **ADR-01**: gRPC vs REST communication strategy for high-throughput client streaming.
- **ADR-02**: Circuit breaker pattern implemented for downstream client resilience.
- **ADR-03**: Zero-trust mTLS with RS256 JWT tokens terminating at Istio Gateway.
- **ADR-06**: In-memory cache defense to mitigate THR-05 key leakage.

### 4. System Invariants & Formal Guarantees
- **INV-01**: Synchronous write-ahead log commit guarantees zero data loss on database mutation.
- **INV-02**: Tenant cryptographic key sovereignty isolated inside FIPS 140-3 validated HSM.
`,
  };
}
